version: '3.8'
services:
  backend:
    container_name: backend-node
    build: 
      context: ./BACKEND
    volumes:  
      - ./BACKEND:/app
      - /app/node_modules
    ports: 
      - "3001:3001"
    command: npm run dev
    networks:
      - network1

  database:
    image: mongo:8.0-rc-jammy
    container_name: database-container
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example-user
      - MONGO_INITDB_ROOT_PASSWORD=secret-password
      - MONGO_INITDB_DATABASE=odontograma
    volumes:
      - db-data:/data/db
    networks:
      - network1

  mongo-express:
    depends_on:
      - database
    image: mongo-express:1.0-20-alpine3.19
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=example-user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret-password
      - ME_CONFIG_MONGODB_SERVER=database
      # - ME_CONFIG_MONGODB_URL=mongodb://example-user:secret-password@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    networks:
      - network1

  frontend:
    container_name: frontend-angular
    build:
      context: ./FRONTEND/odontograma
    ports:
      - "4200:4200"
    volumes:
      - ./FRONTEND/odontograma:/app
      - /app/node_modules
    command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check"
    networks:
      - network1

networks:
  network1:
    driver: bridge

volumes:
  db-data:
